# Generated by Django 5.2.5 on 2025-09-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRFApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
